### PR TITLE
Add benchmark infratructure without actual tests

### PR DESCRIPTION
**Pull request by blindspotbounty**
There is an infrastructure for adding benchmark tests for swift-kafka-client.

### CODE REVIEW

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by blindspotbounty** [comment]
Hm, something strange happens to build:
```
15:54:07 /swift-kafka-client/Sources/Kafka/KafkaConsumer.swift:294:58: error: 'makeSequence(elementType:backPressureStrategy:delegate:)' is deprecated: This method has been deprecated since it defaults to deinit based resource teardown
15:54:07         let sourceAndSequence = NIOAsyncSequenceProducer.makeSequence(
```
Seems not related to these changes

**Comment by FranzBusch** [comment]
Yeah that's caused by our latest NIO release. We have to fix that up as well.

**Comment by blindspotbounty** [comment]
@FranzBusch if I am not wrong, the change is trivial, so I've just put new argument within this PR.

**Pull request merged**
