### PR TITLE
Update to latest librdkafka & add a define for RAND_priv_bytes (#138)

### PR DESCRIPTION
**Pull request by axelandersson**
>Would appreciate a PR for it. I think the solution should be as easy as doing something like this `#define RAND_priv_bytes(x,sz) RAND_bytes((x),(sz))` in a C file where we shim boringssl to openssl.

_Originally posted by @FranzBusch in https://github.com/swift-server/swift-kafka-client/issues/138#issuecomment-1822864000_

As discussed. Let me know if there's a better place for the `#define`.

### CODE REVIEW

**Comment by FranzBusch** [comment]
To which commit did you checkout the rdkafka submodule?

**Comment by axelandersson** [comment]
> To which commit did you checkout the rdkafka submodule?

To this:

```
diff --git Sources/Crdkafka/librdkafka Sources/Crdkafka/librdkafka
index c282ba2..95a542c 160000
--- Sources/Crdkafka/librdkafka
+++ Sources/Crdkafka/librdkafka
@@ -1 +1 @@
-Subproject commit c282ba2423b2694052393c8edb0399a5ef471b3f
+Subproject commit 95a542c87c61d2c45b445f91c73dd5442eb04f3c
```

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Comment by FranzBusch** [comment]
@swift-server-bot test this please

**Review by FranzBusch — APPROVED** [review]
Thanks for doing the work!

**Pull request merged**
